name: frism
channels:
  - defaults
dependencies:
  - python=3.6
  - networkx
  - numpy
  - pandas
  - matplotlib
  - geopandas
  - descartes
  - joblib
  - libspatialindex
  - xlrd
  - libgdal
  - seaborn
